// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRKc-LSgkYqUXUtz_7JPyd4yIMdECpBys',
    appId: '1:587685568487:web:6effa6336a81d158486742',
    messagingSenderId: '587685568487',
    projectId: 'flutter-oz-c014a',
    authDomain: 'flutter-oz-c014a.firebaseapp.com',
    storageBucket: 'flutter-oz-c014a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCywPWoOR5j5j09GQNUhzCoe6U9hXbKQeE',
    appId: '1:587685568487:android:4b91278ebe046cc5486742',
    messagingSenderId: '587685568487',
    projectId: 'flutter-oz-c014a',
    storageBucket: 'flutter-oz-c014a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEfYSfqGHrTh7hTlEC-1d2DeselZW_ap4',
    appId: '1:587685568487:ios:6d40c78fe54ecdcb486742',
    messagingSenderId: '587685568487',
    projectId: 'flutter-oz-c014a',
    storageBucket: 'flutter-oz-c014a.appspot.com',
    iosBundleId: 'com.zeldafly.oz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEfYSfqGHrTh7hTlEC-1d2DeselZW_ap4',
    appId: '1:587685568487:ios:6d40c78fe54ecdcb486742',
    messagingSenderId: '587685568487',
    projectId: 'flutter-oz-c014a',
    storageBucket: 'flutter-oz-c014a.appspot.com',
    iosBundleId: 'com.zeldafly.oz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRKc-LSgkYqUXUtz_7JPyd4yIMdECpBys',
    appId: '1:587685568487:web:f5885b94844e232f486742',
    messagingSenderId: '587685568487',
    projectId: 'flutter-oz-c014a',
    authDomain: 'flutter-oz-c014a.firebaseapp.com',
    storageBucket: 'flutter-oz-c014a.appspot.com',
  );
}
